// @generated by tools/generate_registry.py — DO NOT EDIT.
// Source: registries/*.csv, vendored from IANA.
// Regenerate: python3 tools/fetch_registries.py && python3 tools/generate_registry.py

/// Flags carried by an access token (RFC 9635 §2.1.1, §3.2.1).
///
/// Generated from the IANA registry. A value that is not registered is
/// carried by [`Unregistered`](Self::Unregistered): GNAP is designed to be
/// extended, so an unknown value is not a parse error (RFC 9635 Appendix D).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum AccessTokenFlag {
    /// `bearer`
    Bearer,
    /// `durable`
    Durable,
    /// A value absent from the IANA registry when this file was generated.
    Unregistered(String),
}

impl AccessTokenFlag {
    /// Every registered value, in registry order.
    pub const REGISTERED: &'static [&'static str] = &["bearer", "durable"];

    /// The on-the-wire representation.
    #[must_use]
    pub fn as_str(&self) -> &str {
        match self {
            Self::Bearer => "bearer",
            Self::Durable => "durable",
            Self::Unregistered(s) => s.as_str(),
        }
    }

    /// Returns `false` when the value is absent from the IANA registry.
    #[must_use]
    pub const fn is_registered(&self) -> bool {
        !matches!(self, Self::Unregistered(_))
    }
}

impl From<&str> for AccessTokenFlag {
    fn from(s: &str) -> Self {
        match s {
            "bearer" => Self::Bearer,
            "durable" => Self::Durable,
            other => Self::Unregistered(other.to_owned()),
        }
    }
}

crate::impl_registry_traits!(AccessTokenFlag);

/// Assertion formats (RFC 9635 §3.4.1).
///
/// Generated from the IANA registry. A value that is not registered is
/// carried by [`Unregistered`](Self::Unregistered): GNAP is designed to be
/// extended, so an unknown value is not a parse error (RFC 9635 Appendix D).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum AssertionFormat {
    /// `id_token`
    IdToken,
    /// `saml2`
    Saml2,
    /// A value absent from the IANA registry when this file was generated.
    Unregistered(String),
}

impl AssertionFormat {
    /// Every registered value, in registry order.
    pub const REGISTERED: &'static [&'static str] = &["id_token", "saml2"];

    /// The on-the-wire representation.
    #[must_use]
    pub fn as_str(&self) -> &str {
        match self {
            Self::IdToken => "id_token",
            Self::Saml2 => "saml2",
            Self::Unregistered(s) => s.as_str(),
        }
    }

    /// Returns `false` when the value is absent from the IANA registry.
    #[must_use]
    pub const fn is_registered(&self) -> bool {
        !matches!(self, Self::Unregistered(_))
    }
}

impl From<&str> for AssertionFormat {
    fn from(s: &str) -> Self {
        match s {
            "id_token" => Self::IdToken,
            "saml2" => Self::Saml2,
            other => Self::Unregistered(other.to_owned()),
        }
    }
}

crate::impl_registry_traits!(AssertionFormat);

/// Client-facing error codes (RFC 9635 §3.6).
///
/// Generated from the IANA registry. A value that is not registered is
/// carried by [`Unregistered`](Self::Unregistered): GNAP is designed to be
/// extended, so an unknown value is not a parse error (RFC 9635 Appendix D).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ErrorCode {
    /// `invalid_request`
    InvalidRequest,
    /// `invalid_client`
    InvalidClient,
    /// `invalid_interaction`
    InvalidInteraction,
    /// `invalid_flag`
    InvalidFlag,
    /// `invalid_rotation`
    InvalidRotation,
    /// `key_rotation_not_supported`
    KeyRotationNotSupported,
    /// `invalid_continuation`
    InvalidContinuation,
    /// `user_denied`
    UserDenied,
    /// `request_denied`
    RequestDenied,
    /// `unknown_interaction`
    UnknownInteraction,
    /// `unknown_user`
    UnknownUser,
    /// `too_fast`
    TooFast,
    /// `too_many_attempts`
    TooManyAttempts,
    /// A value absent from the IANA registry when this file was generated.
    Unregistered(String),
}

impl ErrorCode {
    /// Every registered value, in registry order.
    pub const REGISTERED: &'static [&'static str] = &[
        "invalid_request",
        "invalid_client",
        "invalid_interaction",
        "invalid_flag",
        "invalid_rotation",
        "key_rotation_not_supported",
        "invalid_continuation",
        "user_denied",
        "request_denied",
        "unknown_interaction",
        "unknown_user",
        "too_fast",
        "too_many_attempts",
    ];

    /// The on-the-wire representation.
    #[must_use]
    pub fn as_str(&self) -> &str {
        match self {
            Self::InvalidRequest => "invalid_request",
            Self::InvalidClient => "invalid_client",
            Self::InvalidInteraction => "invalid_interaction",
            Self::InvalidFlag => "invalid_flag",
            Self::InvalidRotation => "invalid_rotation",
            Self::KeyRotationNotSupported => "key_rotation_not_supported",
            Self::InvalidContinuation => "invalid_continuation",
            Self::UserDenied => "user_denied",
            Self::RequestDenied => "request_denied",
            Self::UnknownInteraction => "unknown_interaction",
            Self::UnknownUser => "unknown_user",
            Self::TooFast => "too_fast",
            Self::TooManyAttempts => "too_many_attempts",
            Self::Unregistered(s) => s.as_str(),
        }
    }

    /// Returns `false` when the value is absent from the IANA registry.
    #[must_use]
    pub const fn is_registered(&self) -> bool {
        !matches!(self, Self::Unregistered(_))
    }
}

impl From<&str> for ErrorCode {
    fn from(s: &str) -> Self {
        match s {
            "invalid_request" => Self::InvalidRequest,
            "invalid_client" => Self::InvalidClient,
            "invalid_interaction" => Self::InvalidInteraction,
            "invalid_flag" => Self::InvalidFlag,
            "invalid_rotation" => Self::InvalidRotation,
            "key_rotation_not_supported" => Self::KeyRotationNotSupported,
            "invalid_continuation" => Self::InvalidContinuation,
            "user_denied" => Self::UserDenied,
            "request_denied" => Self::RequestDenied,
            "unknown_interaction" => Self::UnknownInteraction,
            "unknown_user" => Self::UnknownUser,
            "too_fast" => Self::TooFast,
            "too_many_attempts" => Self::TooManyAttempts,
            other => Self::Unregistered(other.to_owned()),
        }
    }
}

crate::impl_registry_traits!(ErrorCode);

/// Interaction finish methods (RFC 9635 §2.5.2).
///
/// Generated from the IANA registry. A value that is not registered is
/// carried by [`Unregistered`](Self::Unregistered): GNAP is designed to be
/// extended, so an unknown value is not a parse error (RFC 9635 Appendix D).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum InteractionFinishMethod {
    /// `redirect`
    Redirect,
    /// `push`
    Push,
    /// A value absent from the IANA registry when this file was generated.
    Unregistered(String),
}

impl InteractionFinishMethod {
    /// Every registered value, in registry order.
    pub const REGISTERED: &'static [&'static str] = &["redirect", "push"];

    /// The on-the-wire representation.
    #[must_use]
    pub fn as_str(&self) -> &str {
        match self {
            Self::Redirect => "redirect",
            Self::Push => "push",
            Self::Unregistered(s) => s.as_str(),
        }
    }

    /// Returns `false` when the value is absent from the IANA registry.
    #[must_use]
    pub const fn is_registered(&self) -> bool {
        !matches!(self, Self::Unregistered(_))
    }
}

impl From<&str> for InteractionFinishMethod {
    fn from(s: &str) -> Self {
        match s {
            "redirect" => Self::Redirect,
            "push" => Self::Push,
            other => Self::Unregistered(other.to_owned()),
        }
    }
}

crate::impl_registry_traits!(InteractionFinishMethod);

/// Interaction start modes (RFC 9635 §2.5.1).
///
/// Generated from the IANA registry. A value that is not registered is
/// carried by [`Unregistered`](Self::Unregistered): GNAP is designed to be
/// extended, so an unknown value is not a parse error (RFC 9635 Appendix D).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum InteractionStartMode {
    /// `redirect`
    Redirect,
    /// `app`
    App,
    /// `user_code`
    UserCode,
    /// `user_code_uri`
    UserCodeUri,
    /// A value absent from the IANA registry when this file was generated.
    Unregistered(String),
}

impl InteractionStartMode {
    /// Every registered value, in registry order.
    pub const REGISTERED: &'static [&'static str] =
        &["redirect", "app", "user_code", "user_code_uri"];

    /// The on-the-wire representation.
    #[must_use]
    pub fn as_str(&self) -> &str {
        match self {
            Self::Redirect => "redirect",
            Self::App => "app",
            Self::UserCode => "user_code",
            Self::UserCodeUri => "user_code_uri",
            Self::Unregistered(s) => s.as_str(),
        }
    }

    /// Returns `false` when the value is absent from the IANA registry.
    #[must_use]
    pub const fn is_registered(&self) -> bool {
        !matches!(self, Self::Unregistered(_))
    }
}

impl From<&str> for InteractionStartMode {
    fn from(s: &str) -> Self {
        match s {
            "redirect" => Self::Redirect,
            "app" => Self::App,
            "user_code" => Self::UserCode,
            "user_code_uri" => Self::UserCodeUri,
            other => Self::Unregistered(other.to_owned()),
        }
    }
}

crate::impl_registry_traits!(InteractionStartMode);

/// Public key formats (RFC 9635 §7.1).
///
/// Generated from the IANA registry. A value that is not registered is
/// carried by [`Unregistered`](Self::Unregistered): GNAP is designed to be
/// extended, so an unknown value is not a parse error (RFC 9635 Appendix D).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum KeyFormat {
    /// `jwk`
    Jwk,
    /// `cert`
    Cert,
    /// `cert#S256`
    CertS256,
    /// A value absent from the IANA registry when this file was generated.
    Unregistered(String),
}

impl KeyFormat {
    /// Every registered value, in registry order.
    pub const REGISTERED: &'static [&'static str] = &["jwk", "cert", "cert#S256"];

    /// The on-the-wire representation.
    #[must_use]
    pub fn as_str(&self) -> &str {
        match self {
            Self::Jwk => "jwk",
            Self::Cert => "cert",
            Self::CertS256 => "cert#S256",
            Self::Unregistered(s) => s.as_str(),
        }
    }

    /// Returns `false` when the value is absent from the IANA registry.
    #[must_use]
    pub const fn is_registered(&self) -> bool {
        !matches!(self, Self::Unregistered(_))
    }
}

impl From<&str> for KeyFormat {
    fn from(s: &str) -> Self {
        match s {
            "jwk" => Self::Jwk,
            "cert" => Self::Cert,
            "cert#S256" => Self::CertS256,
            other => Self::Unregistered(other.to_owned()),
        }
    }
}

crate::impl_registry_traits!(KeyFormat);

/// Key proofing methods (RFC 9635 §7.3).
///
/// Generated from the IANA registry. A value that is not registered is
/// carried by [`Unregistered`](Self::Unregistered): GNAP is designed to be
/// extended, so an unknown value is not a parse error (RFC 9635 Appendix D).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum KeyProofingMethod {
    /// `httpsig`
    Httpsig,
    /// `mtls`
    Mtls,
    /// `jwsd`
    Jwsd,
    /// `jws`
    Jws,
    /// A value absent from the IANA registry when this file was generated.
    Unregistered(String),
}

impl KeyProofingMethod {
    /// Every registered value, in registry order.
    pub const REGISTERED: &'static [&'static str] = &["httpsig", "mtls", "jwsd", "jws"];

    /// The on-the-wire representation.
    #[must_use]
    pub fn as_str(&self) -> &str {
        match self {
            Self::Httpsig => "httpsig",
            Self::Mtls => "mtls",
            Self::Jwsd => "jwsd",
            Self::Jws => "jws",
            Self::Unregistered(s) => s.as_str(),
        }
    }

    /// Returns `false` when the value is absent from the IANA registry.
    #[must_use]
    pub const fn is_registered(&self) -> bool {
        !matches!(self, Self::Unregistered(_))
    }
}

impl From<&str> for KeyProofingMethod {
    fn from(s: &str) -> Self {
        match s {
            "httpsig" => Self::Httpsig,
            "mtls" => Self::Mtls,
            "jwsd" => Self::Jwsd,
            "jws" => Self::Jws,
            other => Self::Unregistered(other.to_owned()),
        }
    }
}

crate::impl_registry_traits!(KeyProofingMethod);

/// Error codes for the RS-facing API (RFC 9767 §3.5).
///
/// Generated from the IANA registry. A value that is not registered is
/// carried by [`Unregistered`](Self::Unregistered): GNAP is designed to be
/// extended, so an unknown value is not a parse error (RFC 9635 Appendix D).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum RsErrorCode {
    /// `invalid_request`
    InvalidRequest,
    /// `invalid_resource_server`
    InvalidResourceServer,
    /// `invalid_access`
    InvalidAccess,
    /// A value absent from the IANA registry when this file was generated.
    Unregistered(String),
}

impl RsErrorCode {
    /// Every registered value, in registry order.
    pub const REGISTERED: &'static [&'static str] = &[
        "invalid_request",
        "invalid_resource_server",
        "invalid_access",
    ];

    /// The on-the-wire representation.
    #[must_use]
    pub fn as_str(&self) -> &str {
        match self {
            Self::InvalidRequest => "invalid_request",
            Self::InvalidResourceServer => "invalid_resource_server",
            Self::InvalidAccess => "invalid_access",
            Self::Unregistered(s) => s.as_str(),
        }
    }

    /// Returns `false` when the value is absent from the IANA registry.
    #[must_use]
    pub const fn is_registered(&self) -> bool {
        !matches!(self, Self::Unregistered(_))
    }
}

impl From<&str> for RsErrorCode {
    fn from(s: &str) -> Self {
        match s {
            "invalid_request" => Self::InvalidRequest,
            "invalid_resource_server" => Self::InvalidResourceServer,
            "invalid_access" => Self::InvalidAccess,
            other => Self::Unregistered(other.to_owned()),
        }
    }
}

crate::impl_registry_traits!(RsErrorCode);

/// Access token formats (RFC 9767 §2.2).
///
/// Generated from the IANA registry. A value that is not registered is
/// carried by [`Unregistered`](Self::Unregistered): GNAP is designed to be
/// extended, so an unknown value is not a parse error (RFC 9635 Appendix D).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum TokenFormat {
    /// `jwt-signed`
    JwtSigned,
    /// `jwt-encrypted`
    JwtEncrypted,
    /// `macaroon`
    Macaroon,
    /// `biscuit`
    Biscuit,
    /// `zcap`
    Zcap,
    /// A value absent from the IANA registry when this file was generated.
    Unregistered(String),
}

impl TokenFormat {
    /// Every registered value, in registry order.
    pub const REGISTERED: &'static [&'static str] =
        &["jwt-signed", "jwt-encrypted", "macaroon", "biscuit", "zcap"];

    /// The on-the-wire representation.
    #[must_use]
    pub fn as_str(&self) -> &str {
        match self {
            Self::JwtSigned => "jwt-signed",
            Self::JwtEncrypted => "jwt-encrypted",
            Self::Macaroon => "macaroon",
            Self::Biscuit => "biscuit",
            Self::Zcap => "zcap",
            Self::Unregistered(s) => s.as_str(),
        }
    }

    /// Returns `false` when the value is absent from the IANA registry.
    #[must_use]
    pub const fn is_registered(&self) -> bool {
        !matches!(self, Self::Unregistered(_))
    }
}

impl From<&str> for TokenFormat {
    fn from(s: &str) -> Self {
        match s {
            "jwt-signed" => Self::JwtSigned,
            "jwt-encrypted" => Self::JwtEncrypted,
            "macaroon" => Self::Macaroon,
            "biscuit" => Self::Biscuit,
            "zcap" => Self::Zcap,
            other => Self::Unregistered(other.to_owned()),
        }
    }
}

crate::impl_registry_traits!(TokenFormat);

// --- field-name registries -------------------------------------------
// Used to check whether an extension field is registered (Appendix D).

/// Registered fields — RFC 9635 §9.
pub const AS_DISCOVERY_FIELDS: &[&str] = &[
    "grant_request_endpoint",
    "interaction_start_modes_supported",
    "interaction_finish_methods_supported",
    "key_proofs_supported",
    "sub_id_formats_supported",
    "assertion_formats_supported",
    "key_rotation_supported",
];

/// Registered fields — RFC 9635 §2.3.2.
pub const CLIENT_DISPLAY_FIELDS: &[&str] = &["name", "uri", "logo_uri"];

/// Registered fields — RFC 9635 §2.3.
pub const CLIENT_INSTANCE_FIELDS: &[&str] = &["key", "class_id", "display"];

/// Registered fields — RFC 9635 §2.
pub const GRANT_REQUEST_PARAMETERS: &[&str] = &[
    "access_token",
    "subject",
    "client",
    "user",
    "interact",
    "interact_ref",
    "existing_access_token",
];

/// Registered fields — RFC 9635 §3.
pub const GRANT_RESPONSE_PARAMETERS: &[&str] = &[
    "continue",
    "access_token",
    "interact",
    "subject",
    "instance_id",
    "error",
];

/// Registered fields — RFC 9635 §2.5.3.
pub const INTERACTION_HINTS: &[&str] = &["ui_locales"];

/// Registered fields — RFC 9635 §3.3.
pub const INTERACTION_MODE_RESPONSES: &[&str] = &[
    "redirect",
    "app",
    "user_code",
    "user_code_uri",
    "finish",
    "expires_in",
];

/// Registered fields — RFC 9635 §2.2.
pub const SUBJECT_REQUEST_FIELDS: &[&str] = &["sub_id_formats", "assertion_formats", "sub_ids"];

/// Registered fields — RFC 9635 §3.4.
pub const SUBJECT_RESPONSE_FIELDS: &[&str] = &["sub_ids", "assertions", "updated_at"];

/// Registered fields — RFC 9767 §3.4.
pub const RESOURCE_SET_REQUEST_PARAMETERS: &[&str] = &[
    "access",
    "resource_server",
    "token_formats_supported",
    "token_introspection_required",
];

/// Registered fields — RFC 9767 §3.4.
pub const RESOURCE_SET_RESPONSE_PARAMETERS: &[&str] = &[
    "resource_reference",
    "instance_id",
    "introspection_endpoint",
];

/// Registered fields — RFC 9767 §3.1.
pub const RS_DISCOVERY_FIELDS: &[&str] = &[
    "introspection_endpoint",
    "token_formats_supported",
    "resource_registration_endpoint",
    "grant_request_endpoint",
    "key_proofs_supported",
];

/// Registered fields — RFC 9767 §3.3.
pub const INTROSPECTION_REQUEST_FIELDS: &[&str] =
    &["access_token", "proof", "resource_server", "access"];

/// Registered fields — RFC 9767 §3.3.
pub const INTROSPECTION_RESPONSE_FIELDS: &[&str] = &[
    "active",
    "access",
    "key",
    "flags",
    "exp",
    "iat",
    "nbf",
    "aud",
    "sub",
    "iss",
    "instance_id",
];
